# Generated by Django 5.0.2 on 2024-02-14 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default=datetime.datetime(2024, 2, 14, 9, 5, 11, 811269, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
    ]
